# Generated by Django 5.1.4 on 2025-05-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hoa hồng'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Tên'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Giá bán'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contract',
            name='end_date',
            field=models.DateField(verbose_name='Ngày kết thúc'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Lương'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(verbose_name='Ngày bắt đầu'),
        ),
    ]
