# Generated by Django 5.1.4 on 2025-05-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_commission_contract_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='contract_number',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='salary',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='contract',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hoa hồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Giá bán'),
        ),
    ]
