# Generated by Django 5.1.4 on 2025-05-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_commission_alter_contract_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hoa hồng'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Tên'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Giá bán'),
        ),
        migrations.DeleteModel(
            name='UserContract',
        ),
    ]
