# Generated by Django 5.1.4 on 2025-04-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0001_initial'),
        ('user', '0011_remove_employee_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='employee_id',
            new_name='contract_id',
        ),
        migrations.RemoveField(
            model_name='contract',
            name='contract_code',
        ),
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='user.employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract',
            name='status',
            field=models.CharField(choices=[('pending', 'Đang chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20),
        ),
    ]
