# Generated by Django 5.1.4 on 2025-04-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0002_rename_employee_id_contract_contract_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='status',
        ),
    ]
