# Generated by Django 5.1.4 on 2025-04-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0003_remove_contract_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
