# Generated by Django 5.1.4 on 2025-04-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0004_contract_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
