# Generated by Django 5.1.4 on 2025-04-06 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary_level',
            field=models.IntegerField(default=1),
        ),
    ]
