# Generated by Django 5.1.4 on 2025-04-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_head_alter_department_name'),
        ('user', '0006_alter_employee_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='department_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='department.department'),
        ),
    ]
