# Generated by Django 5.1.4 on 2025-04-13 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_employee_department_name_alter_employee_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='department_name',
        ),
    ]
