# Generated by Django 5.1.4 on 2025-04-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_employee_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='position',
        ),
    ]
