# Generated by Django 5.1.4 on 2025-05-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_salaryhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='training_status',
            field=models.CharField(choices=[('new', 'Chưa đào tạo'), ('in_progress', 'Đang đào tạo'), ('done', 'Đã đào tạo')], default='new', max_length=20),
        ),
    ]
