# Generated by Django 5.1.4 on 2025-05-11 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xử lý'), ('in_progress', 'Đang thực hiện'), ('completed', 'Hoàn thành'), ('ended', 'Kết thúc')], default='pending', max_length=20),
        ),
    ]
